@startuml Administrator
Actor 
participant Console as Console
participant Server as Server
collections Accounts as Accounts
participant Account as "a: Account"
collections Offerings as Offerings
participant Offering as "o: Offering"

group Instructor Creates Offering
  ref over Instructor, Account: User Logs In
end

@enduml