@startuml
Actor Instructor as Instructor
participant Console as Console
collections Accounts as Accounts
participant Account as Account
collections Offerings as Offerings
participant Offering as Offering

group Instructor Creates Offering
  group User Logs In
  end
  Instructor -> Console: createNewOffering()
  Instructor -> Console: accessType, lessonType
  


end

@enduml