@startuml TakingOffering

Actor UserPerson as "User"
participant Console as Console
participant Server as Server
collections Users as Accounts
participant User as "u: User"

group User Logs In
  UserPerson -> Console: username, password
  UserPerson -> Console: login()
  Console -> Server: login(user, password)

  Server -> Accounts: fetchByUsername(username)
  alt user found
    Accounts --> Server: u: User
  else user DNE
    Accounts --> Server: null
    Server --> Console: userDoesNotExistError
    Console --> UserPerson: "Invalid Username"
  end

  
  Server -> Accounts: validatePassword(password)

  alt passwordCheck success
    Accounts --> Server: passwordValid
    Server --> Console: LoginSuccess
    Console --> UserPerson: "Login Successfull"  
  else passwordCheck fails
    Accounts --> Server: passwordError
    Server --> Console: invalidPasswordError
    Console --> UserPerson: "Invalid Password"
  end
end

@enduml
