@startuml Registration
Actor User as User
participant Console as Console
participant Server as Server
collections Accounts as Accounts

group Create account
  alt Create Instructor account
    activate User
    User -> Console ++: check "instructor" checkbox
    Console -> Console: addInstructorInputFields()
    User -> Console:  email, phoneNumber, specialization, city, firstname, lastname, password
  else Create Client Account
    User -> Console:  email, phoneNumber, firstname, lastname, password
  end
  User -> Console: createAccount()

  Console -> Server ++: createAccount(userInfo)
  Server -> Accounts ++: includes(email)
  group email already exist
    Accounts --> Server --: true
    Server -[#red]-> Console: <font color=red> emailAlreadyInUseError
  end
    Accounts --> Server: false
    Server --> Console: success
 
  Server -> Account **: create(userInfo)
  Server -> Accounts: push(account)
  Server --> Console --: successfullyCreatedAccount

  Console -> Console: routeTo(LoginPage)
end

@enduml