@startuml

title Lesson Booking System - Domain Model

object Organization{}
object City{}
object Location{}
object Schedule
object TimeSlot
object Account
object Instructor
object Client
object Guardian
object Administrator
object Offering
object Booking

Account <|-- Instructor
Account <|-- Client
Account <|-- Guardian
Account <|-- Administrator

Organization "1" --> "*" Location : owns

Location "1" --> "1" City : located_in

Location "1" --> "*" Schedule : has

Schedule "1" --> "*" TimeSlot : includes

Instructor "*" --> "*" City : available_in

Offering "1" --> "0..1" Instructor : assigned_to

Offering "1" --> "1" Location : occurs_at

Offering "1" --> "1" TimeSlot : scheduled_at

Client "1" --> "*" Booking : makes

Booking "1" --> "1" Offering : for

Client "0..1" --> "1" Guardian : has

Guardian "1" --> "*" Client : acts_for

Administrator "1" --> "*" Offering : manages

@enduml
