@startuml
skinparam linetype ortho

title Package Diagram

package "DAO" {
  class AdminastrorsDAO
  class BookingsDAO
  class ClientsDAO
  class InstructorsDAO
  class InstructorOfferingsDAO
  class LocationsDAO
  class OfferingsDAO
  class OrganizationsDAO
}

package "models" {
    class Account
    class Adminastrors
    class Bookings
    class Clients
    class Instructor
    class Locations
    class Offerings
    class Organizations
} 

package "services" {
    class AdminastrorService
    class ClientService
    class GuestService
    class InstructorService
    class Mysqlcon
    class RegistrationService
}

class Driver

Driver -> DAO
Driver --> models
Driver -> services

@enduml
