@startuml SystemOperations

object System {
    addSchedule(Schedule schedule)
    getAvailableOfferings()
    addTimeSlot(TimeSlot timeSlot)
    viewAllRecords()
    createOffering(Offering offering)
    deleteAccount(Account account)
    register()
    login()
    registerAvailability()
    viewOfferings()
    takeOffering(Offering offering)
    markAsUnavailable()
    'makeBooking(Offering offering)
    'viewBookings()
    'cancelBooking(Booking booking)
    'handleBooking(Offering offering)
    'cancel()
}

@enduml
