@startuml SystemOperations#2

object System {
    viewLocations()
    viewOfferingsByLocation()
    viewOfferingsByLessonType()
    viewOfferingsByCity()
    viewAllOfferings()
    isRegistered()
    isAdult()
    validatePassword()
    hasCity()
    isSpecializedIn()
    login()
    takeOffering()
    dropOffering()
    addParticipant()
    removeParticipant()
    assignInstructor()
    dropInstructor()
    isFull()
    isEmpty()
    hasInstructor()
    isAvailable()
    login()
    viewBookings()
    performBooking()
    makeBooking()
    makeBookingForMinor()
    cancelBooking()
    login()
    createOffering()
    deleteOffering()
    deleteOfferingForce()
    createLocation()
    deleteAccount()
    viewOfferingBookings()
    deleteBooking()
    createClient()
    createInstructor()
    createAdmin()
    toString()
}

@enduml
