@startuml SystemOperations

object System {
    getAvailableOfferings()
    viewAllRecords()
    createOffering(Offering offering)
    deleteAccount(Account account)
    register()
    login()
    viewOfferings()
    takeOffering(Offering offering)
    assignInstructor(Instructor instructor)
    markAsAvailable()
    addLocation(Location location)
    makeBooking(Offering offering)
    viewBookings()
    cancelBooking(Booking booking)
    handleBooking(Offering offering)
    cancel()
}

@enduml
